# Generated by Django 3.1.1 on 2022-07-14 23:09

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_tipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(blank=True, max_length=30, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(null=True, upload_to=app.models.cargarFotoProducto)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.persona')),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('foto', models.ImageField(null=True, upload_to=app.models.cargarFoto)),
                ('id_tipo', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.DO_NOTHING, to='app.genero')),
            ],
            bases=('app.persona',),
        ),
    ]
